from typing import Callable, overload

from dlup._types import GenericNumber
from dlup.geometry import DlupPoint, DlupPolygon

class Polygon:
    @property
    def fields(self) -> list[str]: ...
    def get_exterior(self) -> list[tuple[float, float]]: ...
    def get_interiors(self) -> list[list[tuple[float, float]]]: ...

def set_polygon_factory(factory: Callable[[Polygon], DlupPolygon]) -> None: ...

class Point:
    @property
    def fields(self) -> list[str]: ...
    def scale(self, scaling: float, origin: DlupPoint) -> None: ...
    def get_coordinates(self) -> tuple[float, float]: ...

def set_point_factory(factory: Callable[[Point], DlupPoint]) -> None: ...

class AnnotationRegion:
    @property
    def polygons(self) -> list[DlupPolygon]: ...
    @property
    def points(self) -> list[DlupPoint]: ...

class GeometryCollection:
    def add_polygon(self, polygon: Polygon) -> None: ...
    def add_point(self, point: Point) -> None: ...
    @property
    def polygons(self) -> list[DlupPolygon]: ...
    @property
    def points(self) -> list[DlupPoint]: ...
    def set_offset(self, offset: tuple[float, float]) -> None: ...
    def rebuild_rtree(self) -> None: ...
    def reindex_polygons(self, index_map: dict[str, int]) -> None: ...
    @overload
    def remove_point(self, index: int) -> None: ...
    @overload
    def remove_point(self, point: DlupPoint) -> None: ...
    @overload
    def remove_polygon(self, index: int) -> None: ...
    @overload
    def remove_polygon(self, polygon: DlupPolygon) -> None: ...
    def sort_polygons(self, key: Callable[[DlupPolygon], int | float | str], reverse: bool) -> None: ...
    @property
    def bounding_box(self) -> tuple[tuple[float, float], tuple[float, float]]: ...
    def size(self) -> int: ...
    def simplify(self, tolerance: float) -> None: ...
    def scale(self, scaling: float) -> None: ...
    def read_region(
        self,
        coordinates: tuple[GenericNumber, GenericNumber],
        scaling: float,
        size: tuple[GenericNumber, GenericNumber],
    ) -> AnnotationRegion: ...
