from typing import Callable, overload

from dlup._types import GenericNumber

class Polygon:
    @property
    def fields(self) -> list[str]: ...
    def get_exterior(self) -> list[tuple[float, float]]: ...
    def get_interiors(self) -> list[list[tuple[float, float]]]: ...
    @property
    def area(self) -> float: ...

def set_polygon_factory(factory: Callable[[Polygon], Polygon]) -> None: ...

class Point:
    @property
    def fields(self) -> list[str]: ...
    def scale(self, scaling: float, origin: Point) -> None: ...
    def get_coordinates(self) -> tuple[float, float]: ...

def set_point_factory(factory: Callable[[Point], Point]) -> None: ...

class AnnotationRegion:
    @property
    def polygons(self) -> list[Polygon]: ...
    @property
    def points(self) -> list[Point]: ...

class GeometryCollection:
    def add_polygon(self, polygon: Polygon) -> None: ...
    def add_point(self, point: Point) -> None: ...
    @property
    def polygons(self) -> list[Polygon]: ...
    @property
    def points(self) -> list[Point]: ...
    def set_offset(self, offset: tuple[float, float]) -> None: ...
    def rebuild_rtree(self) -> None: ...
    def reindex_polygons(self, index_map: dict[str, int]) -> None: ...
    @overload
    def remove_point(self, index: int) -> None: ...
    @overload
    def remove_point(self, point: Point) -> None: ...
    @overload
    def remove_polygon(self, index: int) -> None: ...
    @overload
    def remove_polygon(self, polygon: Polygon) -> None: ...
    def sort_polygons(self, key: Callable[[Polygon], int | float | str | None], reverse: bool) -> None: ...
    @property
    def bounding_box(self) -> tuple[tuple[float, float], tuple[float, float]]: ...
    def size(self) -> int: ...
    def simplify(self, tolerance: float) -> None: ...
    def scale(self, scaling: float) -> None: ...
    def read_region(
        self,
        coordinates: tuple[GenericNumber, GenericNumber],
        scaling: float,
        size: tuple[GenericNumber, GenericNumber],
    ) -> AnnotationRegion: ...
