name: CodeCov
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y meson libgl1-mesa-glx libcairo2-dev libgdk-pixbuf2.0-dev libglib2.0-dev libjpeg-dev libpng-dev libtiff5-dev libxml2-dev libopenjp2-7-dev libsqlite3-dev zlib1g-dev libzstd-dev
        sudo apt install -y libfftw3-dev libexpat1-dev libgsf-1-dev liborc-0.4-dev
    - name: Build and install OpenSlide
      run: |
        git clone https://github.com/openslide/openslide.git
        cd openslide
        meson setup builddir
        meson compile -C builddir
        sudo meson install -C builddir
        cd ..
    - name: Build and install libvips
      run: |
        git clone https://github.com/libvips/libvips.git
        cd libvips
        meson setup builddir --prefix=/usr/local
        meson compile -C builddir
        sudo meson install -C builddir
        sudo ldconfig
        cd ..
    - name: Run Coverage
      run: |
        coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
