name: tox
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy numpy==1.26.4 Cython pybind11 spin meson
        spin build
        python -m pip install -e ".[dev]"
        python -m pip install darwin-py
